import Head from "next/head";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <title>NPC Studio</title>
        <meta name="og:image" content="https://www.npcstudio.xyz/card.png/" />
        <link
          rel="preload"
          href="https://npcstudio.xyz/fonts/InternalRainbows.otf"
          as="font"
          type="font/otf"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href="https://npcstudio.xyz/fonts/Manaspace.ttf"
          as="font"
          type="font/ttf"
          crossOrigin="anonymous"
        />
        <style
          dangerouslySetInnerHTML={{
            __html: `
                @font-face {
                    font-family: "Manaspace";
                    font-weight: 400;
                    src: url("https://npcstudio.xyz/fonts/Manaspace.ttf");
                }

                @font-face {
                  font-family: "Internal Rainbows";
                  font-weight: 400;
                  src: url("https://npcstudio.xyz/fonts/InternalRainbows.ttf");
                }
`,
          }}
        />
      </Head>

      <body>
        {children}
        <script src="//cdn.jsdelivr.net/npm/phaser@3.80.1/dist/phaser.js"></script>
      </body>
    </html>
  );
}
